name: EcoPower
author: plleg
description: A Slimefun Addon that focuses on renewable and climate-friendly power generation
main: me.plleg.ecopower.EcoPowerPlugin
website: https://github.com/plleg/EcoPower

depend: [Slimefun]

version: ${project.version}
api-version: 1.19
